config:
  provider: vsphere
  base_domain: example.com
  cluster_name: ocp46
  cluster_domain: ocp46.example.com
  fips: false
  installer_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  pull_secret: "{{ lookup('file', '~/pull-secret.json') }}"
vcenter:
  ip: 10.0.0.200
  datastore: ds0
  network: 10.0.0.x-24
  service_account_username: administrator@vsphere.local
  service_account_password: Password1!
  admin_username: administrator@vsphere.local
  admin_password: Password1!
  datacenter: LAB
  folder_absolute_path:
  vm_power_state: poweredon
  template_name: rhcos-vmware
download:
  channel: stable
  version: 4.6
  govc: https://github.com/vmware/govmomi/releases/download/v0.23.0/govc_linux_amd64.gz
  fcct: https://github.com/coreos/fcct/releases/download/v0.7.0/fcct-x86_64-unknown-linux-gnu
coredns_vm:
  name: coredns
  ipaddr: 10.0.0.10
  upstream_dns: 8.8.8.8
lb_vm:
  name: lb
  ipaddr: 10.0.0.11
bootstrap_vm:
  name: bootstrap
  ipaddr: 10.0.0.20
master_vms:
  - { name: "master1", ipaddr: "10.0.0.21", cpus: "4", memory_mb: "16384", disk_size_gb: "120"}
  - { name: "master2", ipaddr: "10.0.0.22", cpus: "4", memory_mb: "16384", disk_size_gb: "120"}
  - { name: "master3", ipaddr: "10.0.0.23", cpus: "4", memory_mb: "16384", disk_size_gb: "120"}
worker_vms:
  - { name: "worker1", ipaddr: "10.0.0.24", cpus: "2", memory_mb: "8192", disk_size_gb: "120"}
  - { name: "worker2", ipaddr: "10.0.0.25", cpus: "2", memory_mb: "8192", disk_size_gb: "120"}
static_ip:
  gateway: 10.0.0.1
  netmask: 255.255.255.0
  network_interface_name: ens192
ntp:
  custom: false
  ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
