  - name: Check if the RHCOS template already exists
    shell: "govc find -type m | grep {{ vcenter.template_name }}" # noqa 301
    register: template_exists
    ignore_errors: yes

  - name: Delete RHCOS template if skip_ova=false
    command: "govc vm.destroy {{ vcenter.template_name }}" # noqa 301
    when:
      - skip_ova is not defined
      - template_exists.rc == 0

  - name: Download the ova file
    get_url:
      url: "{{ download.ova }}"
      dest: "{{ playbook_dir }}/downloads/{{ vcenter.template_name }}.ova"
      validate_certs: no
    when: skip_ova is not defined

  - name: Deploy the OVA template into the folder
    command: "govc import.ova --name={{ vcenter.template_name }} --ds={{ vcenter.datastore }} --options={{ playbook_dir }}/roles/deploy_ova/files/options.json {{ playbook_dir }}/downloads/{{ vcenter.template_name }}.ova"
    when: skip_ova is not defined

  - name: Update VM options on the template
    command: "govc vm.change -vm {{ vcenter.folder_absolute_path }}/{{ vcenter.template_name }} -e=disk.EnableUUID=TRUE" # noqa 204
    when: skip_ova is not defined

  - name: Upgrade VM version on the template
    command: "govc vm.upgrade -vm {{ vcenter.folder_absolute_path }}/{{ vcenter.template_name }} -version=15" # noqa 204
    when: skip_ova is not defined
