    - name: Create a dictionary out of the install-config.yaml file
      include_vars:
        file: '{{ playbook_dir }}/install-dir/install-config.yaml'
        name: install_config

    - name: Convert the install_config dict back into YAML for installation
      copy:
        content: "{{ install_config | to_yaml }}"
        dest: "{{ playbook_dir }}/install-dir/install-config.yaml"
        mode: '0664'
